### ISSUE TITLE
Add a message stating that the directory for files was not created at the start of tasks. Or create a directory, and if it is impossible to create a message.

### ISSUE THREAD

**Issue by SergeyMi37** [nlzv/isc_stat#2]

**Comment by nlzv** [comment]
If there is not pointed directory as setting or it is invalid then stat monitor
should log message into cconsole|messages.log.
If stat terminal utility is used to point stat logs directory it will be created.
I'm not sure that it is worth to change something.

**Comment by SergeyMi37** [comment]
Very strange program behavior. Do not report an error in a dialogue, where you can immediately fix it, but stupidly keep silent. Much like a charade. Dig into the code, see the logs.

**Comment by nlzv** [comment]
This is typical behaviour for service.
As example one considers systemctl.
systemctl start ServiceName
in order to know whether service has been started ok
systemctl status ServiceName
Here is the same - show state. If it is not started see log.
Though it is possible to make stat logs dir check before start as consensus.
One check in UI of service start , another one in daemon.

**Comment by nlzv** [comment]
fixed by
[stui check for stat logs dir on monitor start](https://github.com/nlzv/isc_stat/commit/22ff036d726dda9d21de05b292d50731914a51ce)
